#SYMBOL CONFIGURATION
# Format: SYMBOL|EXCHANGE|DIGITS|POINT

GBPJPY|FOREX|5|0.00001
XAUUSD|COMMODITIES|5|0.00001
EURUSD|FOREX|5|0.00001
USDJPY|FOREX|5|0.00001
GBPUSD|FOREX|5|0.00001

# SYMBOLS FOR FUTURE EXPANSION
# SILVER (XAGUSD)
# CRUDE OIL (WTICOUSD)
# US500 (SP500)
# NAS100 (NASDAQ)
